# external server with fake graphql data
# see https://graphqlzero.almansi.me
repository_url: https://graphqlzero.almansi.me/api

# this service api-key
api-key: xxx

spring:
  graphql:
    websocket:
      path: /ws

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
          - metrics
  metrics:
    graphql:
      autotime:
        enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSXXX} [%p] %msg%n"
