# external server with fake graphql data
# see https://graphqlzero.almansi.me
graphql:
  client:
    url: https://graphqlzero.almansi.me/api

spring:
  graphql:
    websocket:
      path: /ws

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
          - metrics

logging:
  file:
    name: demo.log
    max-history: 2 # days history
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSXXX} [%p] %msg%n"
    file:    "%d{yyyy-MM-dd'T'HH:mm:ss.SSXXX} [%p] %msg%n"
